# Generated by Django 2.1.1 on 2018-10-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Login', '0002_auto_20181029_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conform_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
